#spring.application.name=discovery-service
#eureka.instance.hostname=localhost
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#server.port=8761
#eureka.username=${EUREKA_USERNAME:eureka}
#eureka.password=${EUREKA_PASSWORD:password}

spring:
  application:
    name: registry

server:
  port: 8761

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false