apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: discovery-service
  name: discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: discovery-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/foody-default: "true"
        io.kompose.service: discovery-service
    spec:
      containers:
        - env:
            - name: eureka.client.fetchRegistry
              value: "false"
            - name: eureka.client.registerWithEureka
              value: "false"
            - name: spring.application.name
              value: discovery-service
          image: innaxn/foody-discovery-service:latest
          name: discovery-service
          ports:
            - containerPort: 8761
              hostPort: 8761
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
